# Generated by Django 3.0.3 on 2020-04-08 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('create_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adrtype', models.CharField(max_length=1, unique=True)),
                ('street', models.CharField(max_length=80)),
                ('postcode', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=25)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nawapp.Person')),
            ],
        ),
    ]
